---

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36-1

platforms:
  - name: ubuntu-xenial
  - name: ubuntu-trusty
  - name: debian-jessie
  - name: debian-wheezy

suites:
  - name: default
    run_list:
      - recipe[devopsdance-rinetd::_test]
